/**
 * Generates src/core/icons.generated.ts with offline icon data for every
 * icon used in src/, so @iconify/vue never calls api.iconify.design at
 * runtime (required for intranet/offline deployments).
 *
 * Run: pnpm icons:build
 */
import { readdirSync, readFileSync, statSync, writeFileSync } from 'node:fs'
import { dirname, join } from 'node:path'
import { fileURLToPath } from 'node:url'
import { getIcons } from '@iconify/utils'

const root = join(dirname(fileURLToPath(import.meta.url)), '..')
const srcDir = join(root, 'src')
const outFile = join(srcDir, 'core', 'icons.generated.ts')

const PREFIXES = ['mdi', 'solar']
// Icons are written both as `mdi:foo` (Iconify form) and `mdi-foo` (legacy form
// normalized at runtime by normalizeIcon()). Both must be bundled.
const ICON_RE = /["'`](?:mdi|solar)[:-][a-z0-9-]+["'`]/g
const ICON_PARTS_RE = /^["'`](mdi|solar)[:-]([a-z0-9-]+)["'`]$/
const SCAN_EXTENSIONS = new Set(['.vue', '.ts'])

// Menu icons are stored in the backend database and served by
// /api/admin/menu-access/my-menus, so they never appear in the source scan.
// Keep in sync with DEFAULT_MENUS in top-product-system-be menu_access.py.
const BACKEND_MENU_ICONS = {
  mdi: [
    'view-dashboard',
    'trophy',
    'circle-small',
    'database-search',
    'file-upload',
    'compare',
    'file-chart',
    'file-swap',
    'shield-lock',
    'delete-sweep',
  ],
  solar: [],
}

function* walk(dir) {
  for (const entry of readdirSync(dir)) {
    const full = join(dir, entry)
    if (statSync(full).isDirectory()) {
      if (entry === 'node_modules' || entry.startsWith('.')) continue
      yield* walk(full)
    } else if (SCAN_EXTENSIONS.has(entry.slice(entry.lastIndexOf('.')))) {
      yield full
    }
  }
}

const used = new Map(PREFIXES.map((p) => [p, new Set()]))

for (const [prefix, names] of Object.entries(BACKEND_MENU_ICONS)) {
  for (const name of names) used.get(prefix)?.add(name)
}

for (const file of walk(srcDir)) {
  if (file === outFile) continue
  const content = readFileSync(file, 'utf8')
  for (const token of content.match(ICON_RE) ?? []) {
    const parts = ICON_PARTS_RE.exec(token)
    if (parts) used.get(parts[1])?.add(parts[2])
  }
}

const collections = []

for (const prefix of PREFIXES) {
  const names = [...used.get(prefix)].sort()
  if (names.length === 0) continue

  const dataPath = join(root, 'node_modules', '@iconify', 'json', 'json', `${prefix}.json`)
  const full = JSON.parse(readFileSync(dataPath, 'utf8'))
  const subset = getIcons(full, names)
  const resolved = new Set([...Object.keys(subset.icons), ...Object.keys(subset.aliases ?? {})])
  const missing = names.filter((n) => !resolved.has(n))
  if (missing.length > 0) {
    console.warn(`[icons] ${prefix}: not found in @iconify/json: ${missing.join(', ')}`)
  }
  collections.push(subset)
  console.log(`[icons] ${prefix}: bundled ${Object.keys(subset.icons).length} icons`)
}

const header = `// AUTO-GENERATED by scripts/build-icons.mjs. Do not edit by hand.
// Regenerate with: pnpm icons:build
import { addCollection } from '@iconify/vue'

`

const body = collections
  .map((c, i) => `const collection${i} = ${JSON.stringify(c)} as never\n`)
  .join('\n')

const register = `
export function registerOfflineIcons(): void {
${collections.map((_, i) => `  addCollection(collection${i})`).join('\n')}
}
`

writeFileSync(outFile, header + body + register)
console.log(`[icons] wrote ${outFile}`)
